### PR TITLE
Add 'onSwipeVertical' event

### PR DESCRIPTION
**Pull request by infostreams**
Can be used to implement https://github.com/archriss/react-native-image-gallery/issues/14

### CODE REVIEW

**Comment by infostreams** [comment]
Please don't accept this pull request yet... I tried it on an actual phone just now, and it doesn't work as well as it does on the simulator. I will submit a better one in a few days.

**Comment by infostreams** [comment]
Ok, I've adjusted the logic. The 'onSwipeVertical' event is now called whenever the image is swiped up or down, together with a value indicating how much the user swiped. You can then use this event to slowly make the background transparent, or to close the gallery completely when the user has swiped the picture up or down by a certain amount.

**Comment by Exilz** [comment]
This is a much welcome feature, and your code looks clean, thanks.

I don't have time to test it right now but I definitely will soon. Other reviews are appreciated @davidpaulsson

**Comment by infostreams** [comment]
Well, it's working as it is, but I think there are a few other issues need to be resolved before it's as nice & fluid as I want it to be.

The first is that you can indeed move the image up or down, and change the background opacity / close the gallery, but once you release the gesture some part of the code will start moving the image back to it's baseline (central) position in the middle of the screen. This is unfortunate because  it looks ugly and it distracts from the user's intention. I will try to hunt down where this happens and add code to control this behavior.

Second, it appears the gallery itself prefers horizontal gestures over vertical gestures. If you drag the image up, but there's still some horizontal movement, it will somehow cancel out the vertical movement and only display the horizontal movement. Again, distracting. Will try to adjust this as well.

Finally, the event also triggers when you zoom the image with the 'pinch' gesture. This is a straight-out bug that needs to be resolved before you can merge the code :-)

Summary: it works, but it's not yet perfect.

**Comment by infostreams** [comment]
I removed the 'onSwipeVertical' code in favor of adding a new 'onViewTransforming' event that is ultimately tied to the image as it is being displayed on the screen.

This solves the issue with the 'pinch' gesture also triggering the event.

The issue that the image returns to the center after releasing the gesture can be resolved in my own code by adding a `onTransformGestureReleased` handler that returns `true` if `transform.translateY` exceeds a given value.

I tried addressing the preference for horizontal movement as well, but I'm not sure if I've been successful. 

Anyway, apologies for the many commits. It's because I've been copy-pasting my own code into the Github editor, so every changed file automatically becomes a single commit. If possible, just squash them into one when/if you merge.

**Comment by infostreams** [comment]
Ok, this has turned into a mess, mostly because I'm committing while I'm finding & fixing issues. I'll close this pull request and make a proper one once all is done.

**Comment by BazhukovTima** [comment]
Hi, this issue in progress?

**Comment by GuillaumeMunsch** [comment]
@infostreams You made progress on this ? :)

**Pull request closed without merging**
