### PR TITLE
Use getItemLayout

### PR DESCRIPTION
**Pull request by vbuch**
Changes:
* The most important one is reverting the removal of getItemLayout
* Then made sure ViewTransformer does not setState when it is unmounted
* The same thing for ViewPage
* Finally fixed some indentation in createResponder

Reasoning on the first one:
https://github.com/archriss/react-native-image-gallery/issues/61#issuecomment-360369341
https://github.com/archriss/react-native-image-gallery/issues/9#issuecomment-359340300
https://github.com/archriss/react-native-image-gallery/issues/51#issuecomment-360185081
https://github.com/archriss/react-native-image-gallery/pull/47#issuecomment-360453481

### CODE REVIEW

**Comment by vbuch** [comment]
@rskull @jing-wu @alainib
Would love to see some support from you guys. Could you try my fork and check if things work?

**Comment by rskull** [comment]
@vbuch Great work!
I confirmed some bugs is fixed. Look good to me.
thank you :)

**Comment by vbuch** [comment]
@Exilz you thoughts?

**Comment by akirasunny** [comment]
Hi,

Seems like initialPage is still not working on Android when its value is larger than 10. And rather than showing a wrong image instantly, the gallery will change images for a few times and finally stop on the image whose index is 11.

On iOS its performance is perfect though, thanks a lot. But still hope this issue could be fixed on Android.

**Comment by vbuch** [comment]
Strange. If you are using 2.1.4 or my PR it should have a window size of 3 meaning it has no relation to the number 10 at all. I'll give it a try in the weekend.

**Comment by rskull** [comment]
`$ yarn add 'archriss/react-native-image-gallery#63/head'`

I tried this command. Probably, this bug is fixed.

**Comment by wassgha** [comment]
Any progress on this?

**Comment by kyo504** [comment]
I can confirm that now it works as expected. I hope that this will be released soon. 👍

**Comment by enahum** [comment]
The 10th image problem can be fixed by setting the **flatListProps** like `flatListProps={{initialNumToRender: this.state.images.length}}`

**Comment by vbuch** [comment]
@enahum, that's not a good idea in most of the cases. Please read what initialnumtorender does and think how it would affect memory usage.

**Comment by BenWildeman** [comment]
any progress on this?

**Comment by BenWildeman** [comment]
I've just tried using this, the 10th image issue is very real. If you have more than 10 images, once you try to scroll to the 11th, it fails to render. It's not even possible to swipe back to the 10th image when this happens

**Comment by alainib** [comment]
@NitroGhost   stick to version "2.1.4" , it work good

**Comment by vbuch** [comment]
Obviously this does not fix all the issues and people are suggested to use 2.1.4. Closing the PR.

**Pull request closed without merging**
