### PR TITLE
Don’t use getItemLayout

### PR DESCRIPTION
**Pull request by infostreams**
Same reason as https://github.com/archriss/react-native-snap-carousel/commit/ce3bf0689b6506efddf93f5c699b9e5100515b1b

### CODE REVIEW

**Comment by Exilz** [comment]
Shipped in `2.1.5`.

**Comment by vbuch** [comment]
Was this done because of an issue? Where can I see how to reproduce it? @Exilz @infostreams

**Comment by infostreams** [comment]
Well, it broke whenever you did the following:

1. Make a Gallery with a window size and an initialNumToRender
```
<Gallery
   {...props}
    flatListProps={{windowSize: 2, initialNumToRender: 1}}  
  />
```

2. Open the gallery, then close the gallery again
3. Open the gallery on an initialPage that is larger than your windowSize
4. Broken; your user sees a black screen because the item is never rendered.

**Comment by vbuch** [comment]
OK. Thank you. I'll take a look.

**Comment by vbuch** [comment]
Well, I have a gallery of 4 items. I passed in windowSize: 2 with initialNumToRender: 1 and I have no issue browsing around and/or using initialPage

**Comment by infostreams** [comment]
Well perhaps I misremember the exact circumstances, but I'm not making up that it is (or was) broken: 

https://github.com/facebook/react-native/issues/1831 
facebook/react-native#8607
facebook/react-native#13316
facebook/react-native#13202
https://github.com/archriss/react-native-snap-carousel/issues/238

**Comment by vbuch** [comment]
So there was never an issue reported for react-native-image-gallery? But you think the issue was that you needed to scroll for rendering to happen?

**Comment by vbuch** [comment]
@infostreams Here is the discussion on this. https://github.com/archriss/react-native-image-gallery/issues/20#issuecomment-331126424 Could you check and try to remember if it is the same issue?

**Comment by infostreams** [comment]
Not entirely sure why you are accusing me of making things up, but yes - one of the most commented on issues in React Native was also showing its ugly head in this repository. I'm sorry that you can't reproduce it, and I'm sorry that you are having issues with this.

I'm not sure if it's the same bug as #20, but the symptoms do look the same.

**Comment by vbuch** [comment]
Sorry. I'm not accusing anyone of anything. Just trying to make sure the lib works as expected. I see there is a regression and I am sure that it is fighting an issue that is not an issue with the lib but with the rest of people's apps. FlatList does some thing "afterinteraction". If you have something that blocks the queue, you wn't get a render. So... that's what the real problem is. It's a problem with usage and not with how the lib works.

**Pull request closed without merging**
